services:
  - type: web
    name: popups-by-shivani
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DIALECT
        value: org.hibernate.dialect.TiDBDialect
